Remove duplicate package entries in test snippets
This could be the reason for the exceptions in the JSR223 API (compileAndLint).

org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_51