Update spek framework to 2.0.13 (#3070)
* Update spek framework to 2.0.13

Release note:
https://github.com/spekframework/spek/releases/tag/2.0.13

* Remove duplicate package entries in test snippets

This could be the reason for the exceptions in the JSR223 API (compileAndLint).

org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_51

* Remove redundant package entry in test snippets

Duplicate package entries could be the reason for the exceptions in the JSR223 API (compileAndLint).

org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_51

* Use new spek timeout property

This fixes the issued warning by the spek framework.
SPEK2_TIMEOUT is deprecated please use spek2.execution.test.timeout instead