Remove redundant package entry in test snippets
Duplicate package entries could be the reason for the exceptions in the JSR223 API (compileAndLint).

org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_51