Inline nested classes visibility tests (#2379)
* Inline test cases of NestedClassesVisibility

* Rename enums

* Fix test case in UnusedPrivateClassSpec

does not report (companion-)object/named-dot references

org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_78
File being compiled at position: (2,40) in /Line_78.kts
The root cause org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException was thrown at: org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)