SwallowedException: Fix ignoring exceptions in the catch body
What all by default ignored exceptions have in common is that none of
their constructors allows to pass an exception as the cause. Thus, it
does not make sense to complain when these are used in the catch body to
replace the original exception.

Fixes #3524.